In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [3]:
dataset = pd.read_csv("Crop_recommendation.csv")
dataset.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [4]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[ 90.          42.          43.         ...  82.00274423   6.50298529
  202.9355362 ]
 [ 85.          58.          41.         ...  80.31964408   7.03809636
  226.6555374 ]
 [ 60.          55.          44.         ...  82.3207629    7.84020714
  263.9642476 ]
 ...
 [118.          33.          30.         ...  67.22512329   6.36260785
  173.3228386 ]
 [117.          32.          34.         ...  52.12739421   6.75879255
  127.1752928 ]
 [104.          18.          30.         ...  60.39647474   6.77983261
  140.9370415 ]]


In [6]:
print(y)

['rice' 'rice' 'rice' ... 'coffee' 'coffee' 'coffee']


In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[20 20 20 ...  5  5  5]


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 5)

In [9]:
print(X_train)

[[ 31.          53.          16.         ...  85.81675947   6.45200645
   48.54598575]
 [ 90.          39.          43.         ...  82.286484     6.7693455
  190.9684885 ]
 [ 23.         142.         197.         ...  82.03812973   6.00057372
   69.30772897]
 ...
 [ 83.          21.          28.         ...  60.49244602   7.46690068
  190.2257843 ]
 [102.          25.          50.         ...  92.91440379   6.09966237
   20.36001144]
 [ 47.          46.          52.         ...  91.40301608   6.50228947
  206.3999208 ]]


In [10]:
print(X_test)

[[  6.         140.         205.         ...  82.92903419   6.3130856
   69.8671263 ]
 [ 98.          22.          47.         ...  91.91533173   6.34140092
   28.83568362]
 [ 38.          14.          30.         ...  91.20106019   5.57074539
  194.9022136 ]
 ...
 [118.          31.          34.         ...  62.88179198   6.12379606
  181.4170812 ]
 [ 90.          86.          52.         ...  81.95580471   5.79326026
  119.0856171 ]
 [ 27.          74.          20.         ...  59.96669215   5.85981342
   91.95792434]]


In [11]:
print(y_train)

[14  8  7 ...  5 15 17]


In [12]:
print(y_test)

[ 7 15  4  3 21 17 17 19 18  0  4 17 19 11  2  3  6 15 13 19 15  3  5 19
  2  8 16 21 20 16  0 13  8  8  1 13 17 14  9  2 12  3 11 17  1  2  4 16
 16 11  5 13 18 16 12 16 15 18 14 13  6  2  3  6 14 14  3 17  4  1 20 11
 19 21  1  9 17  0  7  3  3  1  0 11  0 15  1  3 20 17 18 16 12  5 15 19
 18 21  5  7 20  4 11 11 13  2 16 18 18 11 18 12 12 19 10  2 18 15  0 10
  4 15 10 11 12  5  6  2  5 18  2 11  4  5 16  4 14  2 11  0 16 11  0 17
 15 19  2 19 13 14  7  1 10 20 18  5 14 13 21  8 10  0 20 14 14 16  8  9
 18 18 15  7 11 12  9  3 21 19 10 10 21  7 17  5  0  4 21 17  6  8  5  3
  0 19 17  7 11 21  4  1 17 11  2  6 20 13  5  4 11 14 13 10  3  6 15 21
 11 11  2 15 17  0 16  5  0  6 20 21 17 16 21  3 21 20  6 14 13 15  2 18
 13 16  0 10  5  8 15  9 21 10 21 16 18 18  4  7 12  9 10  4 19  5  0  7
 15  2 15 20 13 20 13  2 17  8  5  5 12  1  5 13 14 16 18  9 16  8 20 10
  9 11  1  7  2 11 11  0  6 20 21  8  3 11  4 16 20 15 19  7 21 10  1  5
 10  3  5 16  9 21  2  6 10 18 10 12 12  9 13 17  8

In [13]:
#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.fit_transform(X_test)

In [14]:
print(X_train)

[[ 31.          53.          16.         ...  85.81675947   6.45200645
   48.54598575]
 [ 90.          39.          43.         ...  82.286484     6.7693455
  190.9684885 ]
 [ 23.         142.         197.         ...  82.03812973   6.00057372
   69.30772897]
 ...
 [ 83.          21.          28.         ...  60.49244602   7.46690068
  190.2257843 ]
 [102.          25.          50.         ...  92.91440379   6.09966237
   20.36001144]
 [ 47.          46.          52.         ...  91.40301608   6.50228947
  206.3999208 ]]


In [15]:
print(X_test)

[[  6.         140.         205.         ...  82.92903419   6.3130856
   69.8671263 ]
 [ 98.          22.          47.         ...  91.91533173   6.34140092
   28.83568362]
 [ 38.          14.          30.         ...  91.20106019   5.57074539
  194.9022136 ]
 ...
 [118.          31.          34.         ...  62.88179198   6.12379606
  181.4170812 ]
 [ 90.          86.          52.         ...  81.95580471   5.79326026
  119.0856171 ]
 [ 27.          74.          20.         ...  59.96669215   5.85981342
   91.95792434]]


In [16]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors =1 , metric = 'minkowski')
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [17]:
print(classifier.predict(([[71, 54, 16, 22.61359953, 63.69070564, 5.749914421, 87.75953857]])))

[11]


In [18]:
y_pred = classifier.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 13  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 13  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 27  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

In [20]:
accuracy_score(y_test, y_pred)

0.9886363636363636

In [21]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        24
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        22
           3       1.00      1.00      1.00        19
           4       1.00      1.00      1.00        20
           5       1.00      1.00      1.00        25
           6       1.00      1.00      1.00        13
           7       1.00      1.00      1.00        17
           8       0.81      0.87      0.84        15
           9       1.00      1.00      1.00        16
          10       1.00      1.00      1.00        18
          11       1.00      1.00      1.00        27
          12       1.00      1.00      1.00        18
          13       1.00      1.00      1.00        22
          14       1.00      1.00      1.00        19
          15       1.00      1.00      1.00        24
          16       1.00      1.00      1.00        23
          17       1.00    

In [603]:
#model save

import pickle
file=open("model.pkl",'wb')
pickle.dump(classifier,file)