In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
df=pd.read_csv('Crop_recommendation.csv')
df.head(5)

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [3]:
copy_df=np.copy(df)

In [4]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [5]:
print(X)

[[ 90.          42.          43.         ...  82.00274423   6.50298529
  202.9355362 ]
 [ 85.          58.          41.         ...  80.31964408   7.03809636
  226.6555374 ]
 [ 60.          55.          44.         ...  82.3207629    7.84020714
  263.9642476 ]
 ...
 [118.          33.          30.         ...  67.22512329   6.36260785
  173.3228386 ]
 [117.          32.          34.         ...  52.12739421   6.75879255
  127.1752928 ]
 [104.          18.          30.         ...  60.39647474   6.77983261
  140.9370415 ]]


In [6]:
print(y)

['rice' 'rice' 'rice' ... 'coffee' 'coffee' 'coffee']


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state = 3)

In [8]:
print(X_train)

[[ 60.          61.          78.         ...  19.83643308   6.31715321
   94.03659867]
 [ 95.          39.          36.         ...  83.15250801   5.56139864
  285.2493645 ]
 [  0.         123.         205.         ...  92.96129462   5.79099305
  121.1349176 ]
 ...
 [ 36.          29.          13.         ...  90.91510525   7.82950725
  109.7513927 ]
 [ 18.          14.          11.         ...  90.00621688   6.55081412
  117.1311498 ]
 [ 37.           5.          34.         ...  93.84150618   5.77903267
  152.4238712 ]]


In [9]:
print(X_test)

[[ 31.          68.          45.         ...  90.07600528   6.93831336
  196.2408242 ]
 [  0.          23.          15.         ...  93.37488907   7.59872906
  109.8585753 ]
 [ 23.           7.          34.         ...  91.52421214   5.8520382
  134.1279669 ]
 ...
 [ 93.          22.          48.         ...  91.52291141   6.77698797
   21.90440445]
 [ 13.          28.          33.         ...  95.64807631   5.68697297
  151.0761899 ]
 [ 94.           5.          55.         ...  91.89216849   6.08568234
   26.88372572]]


In [10]:
print(y_train)


['chickpea' 'rice' 'apple' ... 'orange' 'orange' 'coconut']


In [11]:
print(y_test)


['papaya' 'orange' 'coconut' 'coconut' 'pomegranate' 'grapes' 'mango'
 'coconut' 'pomegranate' 'lentil' 'mothbeans' 'papaya' 'coffee'
 'pigeonpeas' 'muskmelon' 'muskmelon' 'banana' 'pigeonpeas' 'mango'
 'chickpea' 'cotton' 'grapes' 'blackgram' 'kidneybeans' 'kidneybeans'
 'jute' 'kidneybeans' 'rice' 'kidneybeans' 'orange' 'muskmelon' 'grapes'
 'mothbeans' 'grapes' 'rice' 'maize' 'watermelon' 'lentil' 'coconut'
 'papaya' 'mango' 'jute' 'banana' 'lentil' 'grapes' 'kidneybeans' 'maize'
 'coffee' 'chickpea' 'apple' 'kidneybeans' 'jute' 'blackgram' 'chickpea'
 'mungbean' 'jute' 'coffee' 'mango' 'mothbeans' 'muskmelon' 'coconut'
 'kidneybeans' 'mothbeans' 'chickpea' 'blackgram' 'coffee' 'watermelon'
 'apple' 'watermelon' 'apple' 'orange' 'mungbean' 'orange' 'kidneybeans'
 'grapes' 'mothbeans' 'jute' 'watermelon' 'muskmelon' 'cotton' 'grapes'
 'coconut' 'orange' 'grapes' 'mothbeans' 'pomegranate' 'muskmelon'
 'mungbean' 'maize' 'jute' 'pigeonpeas' 'chickpea' 'papaya' 'pigeonpeas'
 'watermelon

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=sc.fit_transform(X_train)


In [13]:
print(X_train)

[[ 0.25321203  0.2281757   0.59413512 ... -2.34157276 -0.19226354
  -0.16363251]
 [ 1.19357864 -0.44286814 -0.23752804 ...  0.52194349 -1.17095166
   3.33526331]
 [-1.35884502  2.11929924  3.10892611 ...  0.96555311 -0.87363116
   0.33222452]
 ...
 [-0.39161079 -0.74788806 -0.69296263 ...  0.87301268  1.76620685
   0.12392374]
 [-0.8752279  -1.20541795 -0.73256563 ...  0.83190754  0.110323
   0.25896181]
 [-0.36474317 -1.47993588 -0.27713105 ...  1.00536133 -0.88911964
   0.90476364]]


In [14]:
X_test=sc.fit_transform(X_test)


In [15]:
print(X_test)

[[-0.54593574  0.45246271 -0.07355299 ...  0.83716015  0.58147425
   1.61997475]
 [-1.41575976 -0.88148037 -0.65984493 ...  0.98164753  1.42844366
   0.0794735 ]
 [-0.77040645 -1.35577124 -0.2885267  ...  0.90058997 -0.81165105
   0.51228265]
 ...
 [ 1.19371231 -0.91112355 -0.01492379 ...  0.900533    0.3745778
  -1.48906069]
 [-1.05099485 -0.73326447 -0.30806976 ...  1.08121056 -1.02334378
   0.81452946]
 [ 1.22177115 -1.4150576   0.12187766 ...  0.91670604 -0.5120073
  -1.40026176]]


In [16]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,y_train)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [17]:
print(classifier.predict(sc.transform([[70, 44, 19, 23.3169, 73.4542, 5.85261, 94.2971 ]])))

['maize']


In [18]:
y_pred=classifier.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

In [20]:
accuracy_score(y_test, y_pred)

0.9727272727272728

In [21]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       apple       1.00      1.00      1.00        17
      banana       1.00      1.00      1.00        14
   blackgram       0.90      1.00      0.95        19
    chickpea       1.00      1.00      1.00        22
     coconut       0.96      1.00      0.98        26
      coffee       1.00      1.00      1.00        25
      cotton       0.94      1.00      0.97        17
      grapes       1.00      1.00      1.00        24
        jute       0.74      0.94      0.83        18
 kidneybeans       1.00      1.00      1.00        21
      lentil       1.00      1.00      1.00        19
       maize       1.00      0.95      0.97        19
       mango       1.00      1.00      1.00        21
   mothbeans       1.00      0.94      0.97        18
    mungbean       1.00      1.00      1.00        16
   muskmelon       1.00      1.00      1.00        23
      orange       1.00      0.95      0.98        21
      papaya       0.94    